### ISSUE TITLE
tutorial texte

### ISSUE THREAD

**Issue by johannesmadest** [fansensGER/sgj2020ss#48]

**Comment by ge36met** [comment]
Texte:
- [x] bewege a & d zum laufen
- [x] drücke space zum springen
- [x] drücke f um mit objekten zu interagieren und bekomme eine neue Fähigkeit
- [x] Erde - halte die linke maustause auf dem stein gedrückt, um ihn zu bewegen
- [x] schalte alle vier fähigkeiten frei um den endgegner zu besiegen
- [x] mit q & w kannst du zwischen den fähigkeiten wechseln
- [x] Feuer - klicke auf das Feuer und ziehe es auf brennbare gegenstände
- [x] Luft - ziehe den mauszeiger um in die richtung vom pfeil zu fliegen
- [x] Wasser - ziehe den mauszeiger um in der richtung eine kurzweilige platform zu erbauen

(durchgang größer machen damit player durch kann)
